### ISSUE TITLE
Unused GPIO ports not initialized with weak pull ups

### ISSUE THREAD

**Issue by joeygold** [microchip-pic-avr-solutions/mclv-48v-300w-an957-dspic33ck256mp508#1]
The project code  bldc.x  doesn't completely initialize the unused ports and correctly terminate them in to weak pull up or down

On  **mclv-48v-300w**  J11 (XPRO1 Header)  Pin 16  - If you touch PIN 16 the motor stops

J11 -PIN16 --> DIM:198 -->dsPIC33CK508MP508 pin 49.

a weak pull up is needed in the code  port_config.c     function
#ifdef TRISD
        **CNPUD = 0x0100;**  // Joseph  Make pin49  weak pullup on MCLV-48V-300W
        TRISD = 0xFFFF;
        LATD  = 0x0000;
![PIN16](https://github.com/user-attachments/assets/45a89b5b-fb68-4481-bee1-f999fe51044c)

**Comment by davind29** [comment]
Thank you, We acknowledge the issue and can confirm that it is a recognized problem. This is because of incorrect configuration of PCI fault, a fix has been implemented and will be included in our upcoming release.

**Comment by joeygold** [comment]
Thankyou. Can you clarify PCI ?

**Comment by davind29** [comment]
The configuration of the PWM Control Inputs (PCI) in this project is incorrect, resulting in the PWM being turned off.
